In [2]:
import numpy as np

In [3]:
my_list = list(range(1000000))

In [6]:
my_arr = np.arange(1000000)

In [7]:
%timeit [x**2 for x in my_list]

74.8 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit my_arr**2

2.02 ms ± 32.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [16]:
np.array([2,3,4,5])

array([2, 3, 4, 5])

In [20]:
np.zeros([10,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [25]:
np.full([3,2],5,dtype=int)

array([[5, 5],
       [5, 5],
       [5, 5]])

In [35]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [333]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [61]:
np.eye(5,5,0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [69]:
np.random.randint(100)

77

In [70]:
from numpy import random as rd

In [74]:
#rd.seed(1)
rd.randint(100)

72

In [89]:
rd.rand(2,2)

array([[0.96326253, 0.17395567],
       [0.12632952, 0.13507916]])

In [87]:
rd.randint(100,size=[3,4])

array([[15, 25, 53, 84],
       [58, 85, 29, 44],
       [37, 22, 91, 54]])

In [90]:
lst = "cat dog bird ant".split()

In [91]:
lst

['cat', 'dog', 'bird', 'ant']

In [103]:
rd.choice(lst)

'bird'

In [130]:
rd.choice(lst,size=[1,4])

array([['cat', 'bird', 'ant', 'bird']], dtype='<U4')

In [129]:
rd.choice(lst,p=[0.1,0.2,0.3,0.4],size=[1,4])

array([['ant', 'dog', 'dog', 'ant']], dtype='<U4')

In [181]:
rd.normal()

-0.9554252623736892

In [256]:
a = np.array([5,6,1,2,3])
a

array([5, 6, 1, 2, 3])

In [216]:
rd.shuffle(a)
a

array([5, 6, 3, 1, 2])

In [214]:
b = rd.permutation(a)
b

array([5, 2, 6, 3, 1])

In [217]:
a

array([5, 6, 3, 1, 2])

In [259]:
a = np.arange(20).reshape(4,5)

In [220]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [261]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [225]:
lst1 = [1,2,3]
lst2 = [4,5,6]

In [262]:
a = np.array(lst1)
b = np.array(lst2)

In [263]:
a+b

array([5, 7, 9])

In [228]:
lst1+lst2

[1, 2, 3, 4, 5, 6]

In [236]:
c = np.array([5])

In [264]:
a*c

array([ 5, 10, 15])

In [265]:
a = np.arange(50).reshape(5,10)
b = np.arange(5).reshape(5,1)

In [266]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [267]:
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [268]:
a+b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53]])

In [272]:
rd.seed(1)
arr = rd.randint(100,size=[7,5])

In [335]:
arr

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [276]:
arr[6,0]

9

In [334]:
arr[1:8]

array([[ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [304]:
arr[[1,2,3] , 1:4]

array([[79, 64, 16],
       [71,  6, 25],
       [18, 84, 11]])

In [309]:
b = [ False,True,True,False,True,True,True]

In [307]:
arr

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [310]:
arr[b]

array([[ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [311]:
arr>50

array([[False, False,  True, False,  True],
       [False,  True,  True, False, False],
       [ True,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True, False],
       [False, False,  True,  True, False]])

In [312]:
arr[arr>50]

array([72, 75, 79, 64, 76, 71, 84, 68, 87, 87, 94, 96, 86, 63, 61])

In [313]:
arr

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [317]:
b

[False, True, True, False, True, True, True]

In [318]:
arr

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [337]:
np.sum(arr,axis = 1)

array([205, 165, 228, 161, 248, 376, 162])

In [327]:
x= 20
y= 30
print(f"answer = {x},{y}")

answer = 20,30


In [328]:
arr

array([[37, 12, 72,  9, 75],
       [ 5, 79, 64, 16,  1],
       [76, 71,  6, 25, 50],
       [20, 18, 84, 11, 28],
       [29, 14, 50, 68, 87],
       [87, 94, 96, 86, 13],
       [ 9,  7, 63, 61, 22]])

In [330]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])